{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# TRANSFERIR ARCHIVOS en PYTHON\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "DRIVER={ODBC Driver 17 for SQL Server};SERVER=10.54.200.90;PORT=1433;DATABASE=data-sync;UID=eettlin;PWD=lOc4l_eXt$24;\n",
      "DRIVER={ODBC Driver 17 for SQL Server};SERVER=10.54.200.90;PORT=1433;DATABASE=data-sync;UID=eettlin;PWD=lOc4l_eXt$24;\n"
     ]
    }
   ],
   "source": [
    "# OBTENER PARÁMETROS de la CONEXIÓN\n",
    "\n",
    "import pyodbc\n",
    "from dotenv import dotenv_values\n",
    "\n",
    "secrets = dotenv_values(\".env\")\n",
    "local_secrets = dotenv_values(\".env.dev\")\n",
    "\n",
    "DRIVER = secrets[\"DRIVER2\"]\n",
    "SERVIDOR = secrets[\"SERVIDOR2\"]\n",
    "PUERTO = secrets[\"PUERTO2\"]\n",
    "BASE = secrets[\"BASE2\"]\n",
    "USUARIO = secrets[\"USUARIO2\"]\n",
    "CONTRASENA = secrets[\"CONTRASENA2\"]\n",
    "\n",
    "constr = f'DRIVER={DRIVER};SERVER={SERVIDOR};PORT={PUERTO};DATABASE={BASE};UID={USUARIO};PWD={CONTRASENA}'\n",
    "\n",
    "conn_str = (\n",
    "    \"DRIVER={ODBC Driver 17 for SQL Server};\"\n",
    "    \"SERVER=10.54.200.90;\"\n",
    "     \"PORT=1433;\"\n",
    "    \"DATABASE=data-sync;\"\n",
    "    \"UID=eettlin;\"\n",
    "    \"PWD=lOc4l_eXt$24;\"\n",
    ")\n",
    "\n",
    "\n",
    "print (constr)\n",
    "print (conn_str)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\eduar\\AppData\\Local\\Temp\\ipykernel_20372\\1839726219.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data = pd.read_sql(query, conn)\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import pyodbc\n",
    "\n",
    "# Configuración de conexión\n",
    "conn_str = f'DRIVER={DRIVER};SERVER={SERVIDOR};PORT={PUERTO};DATBASE={BASE};UID={USUARIO};PWD={CONTRASENA}'\n",
    "\n",
    "conn = pyodbc.connect(conn_str)\n",
    "\n",
    "query = \"\"\"\n",
    "-- Consulta con datos históricos y actuales\n",
    "SELECT [id_tienda]\n",
    "      ,[suc_nombre]\n",
    "      ,[sucursal]\n",
    "      ,[formato]\n",
    "      ,[f_actividad]\n",
    "      ,[terreno]\n",
    "      ,[cubierta]\n",
    "      ,[s_cubierta]\n",
    "      ,[playa]\n",
    "      ,[salon]\n",
    "      ,[deposito]\n",
    "      ,[check_outs]\n",
    "      ,[direccion]\n",
    "      ,[postal]\n",
    "      ,[f_cierre]\n",
    "  FROM [data-sync].[dbo].[M_SUCURSALES_EXT];\n",
    "\"\"\"\n",
    "data = pd.read_sql(query, conn)\n",
    "conn.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "data.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## RUTINA FINAL"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Conexión a SQL Server exitosa.\n",
      "Datos extraídos de SQL Server correctamente.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\eduar\\AppData\\Local\\Temp\\ipykernel_20372\\2711210567.py:44: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data = pd.read_sql(query, conn_sqlserver)\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import pyodbc\n",
    "import psycopg2\n",
    "from sqlalchemy import create_engine\n",
    "\n",
    "# Conexión a SQL Server\n",
    "conn_str_sqlserver = (\n",
    "    \"DRIVER={ODBC Driver 17 for SQL Server};\"\n",
    "    \"SERVER=10.54.200.90;\"\n",
    "    \"PORT=1433;\"\n",
    "    \"DATABASE=data-sync;\"\n",
    "    \"UID=eettlin;\"\n",
    "    \"PWD=lOc4l_eXt$24;\"\n",
    ")\n",
    "\n",
    "try:\n",
    "    conn_sqlserver = pyodbc.connect(conn_str_sqlserver)\n",
    "    print(\"Conexión a SQL Server exitosa.\")\n",
    "except Exception as e:\n",
    "    print(\"Error al conectar a SQL Server:\", e)\n",
    "    exit()\n",
    "\n",
    "# Consulta en SQL Server\n",
    "query = \"\"\"\n",
    "SELECT [id_tienda],\n",
    "       [suc_nombre],\n",
    "       [sucursal],\n",
    "       [formato],\n",
    "       [f_actividad],\n",
    "       [terreno],\n",
    "       [cubierta],\n",
    "       [s_cubierta],\n",
    "       [playa],\n",
    "       [salon],\n",
    "       [deposito],\n",
    "       [check_outs],\n",
    "       [direccion],\n",
    "       [postal],\n",
    "       [f_cierre]\n",
    "  FROM [data-sync].[dbo].[M_SUCURSALES_EXT];\n",
    "\"\"\"\n",
    "\n",
    "try:\n",
    "    data = pd.read_sql(query, conn_sqlserver)\n",
    "    print(\"Datos extraídos de SQL Server correctamente.\")\n",
    "except Exception as e:\n",
    "    print(\"Error al ejecutar la consulta en SQL Server:\", e)\n",
    "    conn_sqlserver.close()\n",
    "    exit()\n",
    "\n",
    "# Cerrar conexión a SQL Server\n",
    "conn_sqlserver.close()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Conexión a PostgreSQL exitosa.\n",
      "Datos insertados en PostgreSQL correctamente.\n",
      "Conexión a PostgreSQL cerrada.\n"
     ]
    }
   ],
   "source": [
    "# Conexión a PostgreSQL\n",
    "conn_str_postgres = \"postgresql://postgres:aladelta10$@140.99.164.229:5432/diarco_data\"\n",
    "\n",
    "try:\n",
    "    engine = create_engine(conn_str_postgres)\n",
    "    conn_postgres = engine.connect()\n",
    "    print(\"Conexión a PostgreSQL exitosa.\")\n",
    "except Exception as e:\n",
    "    print(\"Error al conectar a PostgreSQL:\", e)\n",
    "    exit()\n",
    "\n",
    "# Insertar datos en la tabla m_sucursales_ext\n",
    "try:\n",
    "    data.to_sql('m_sucursales_ext', engine, if_exists='append', index=False)\n",
    "    print(\"Datos insertados en PostgreSQL correctamente.\")\n",
    "except Exception as e:\n",
    "    print(\"Error al insertar datos en PostgreSQL:\", e)\n",
    "finally:\n",
    "    conn_postgres.close()\n",
    "    print(\"Conexión a PostgreSQL cerrada.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
